MMR:
    'Ayeyarwady': "Lower Myanmar"
    'Chin': "Northwest Myanmar"
    'Sagaing': "Northwest Myanmar"
    'Kachin': "Northeast Myanmar" 
    'Kayah': "Southeast Myanmar" 
    'Kayin': "Southeast Myanmar"
    'Magway': "Dry zone"
    'Mandalay': "Dry zone"
    'Mon': "Southeast Myanmar" 
    'Rakhine': "Rakhine"
    'Tanintharyi': "Southeast Myanmar" 
    'Bago (East)': "Lower Myanmar"
    'Bago (West)': "Lower Myanmar"
    'Yangon': "Lower Myanmar" 
    'Shan (East)': "Southeast Myanmar"
    'Shan (North)': "Northeast Myanmar"
    'Shan (South)': "Southeast Myanmar"
    'Nay Pyi Taw': "Dry zone"