weights:
    earthquake: 1
    landslide: 1
    cyclone: 1
    pluvial_defended: 1
    fluvial_defended: 1
    #coastal_defended: 1
    #tsunami_rp100: 0
    #extreme_heat_rp100: 1
    #wildfire_rp10: 0

datasets: 
    - 'worldpop'
    - 'global_earthquake'
    - 'global_landslide'
    - 'global_cyclone'
    #- 'global_tsunami_rp100'
    #- 'global_extreme_heat_rp100'
    #- 'global_wildfire_rp10'

threshold:
    global_earthquake: 0.18
    global_landslide: 3
    global_cyclone: 80
    global_tsunami_rp100: 1
    global_wildfire_rp10: 20
    global_extreme_heat_rp100: 46
    coastal_defended: 50
    pluvial_defended: 50
    fluvial_defended: 50
    

nodata: 
    global_landslide: [0, 255]
    fluvial_defended: [-32768, -32767]
    pluvial_defended: [-32768, -32767]
    coastal_defended: [-32768, -32767]

urls: 
    acled_url: "https://api.acleddata.com/acled/read"
    gbhumanitarian_url: "https://www.geoboundaries.org/api/current/gbHumanitarian/"
    gbopen_url: "https://www.geoboundaries.org/api/current/gbOpen/"
    worldpop_url: "https://data.worldpop.org/GIS/Population/Global_2000_2020/2020/{}/{}_ppp_2020_UNadj.tif"
    global_landslide_url: "https://datacatalogfiles.worldbank.org/ddh-published/0037584/DR0045417/LS_TH_COG.tif"
    global_earthquake_url: "https://cloud.openquake.org/s/6SnFk2f92JEr76H/download/GEM-GSHM_PGA-475y-rock_v2023.zip" 
    global_cyclone_url: "https://data.humdata.org/dataset/6366ac1f-6bed-42e9-b96e-22ef81008931/resource/202221dd-a79d-4ce5-93d7-f34f7514aeb2/download/viento-mundo-tr100-int1-g152.zip" 