hazards:
    earthquake: 1
    landslide: 1
    cyclone: 1
    drought: 1
    heat_stree: 1
    pluvial_defended: 1
    fluvial_defended: 1
    coastal_defended: 1

datasets: 
    - 'worldpop'
    - 'global_earthquake'
    - 'global_landslide'
    - 'global_cyclone'
    - 'global_drought'
    - 'global_heat_stress'

threshold:
    global_earthquake: 0.18
    global_landslide: 3
    global_cyclone: 80
    global_drought: -1
    global_heat_stress: 26
    coastal_defended: 50
    pluvial_defended: 50
    fluvial_defended: 50

nodata: 
    global_landslide: [0, 255]
    fluvial_defended: [-32768, -32767]
    pluvial_defended: [-32768, -32767]
    coastal_defended: [-32768, -32767]

urls: 
    # Source: https://acleddata.com/
    acled_url: "https://api.acleddata.com/acled/read"
    # Source: https://gadm.org/
    gadm_url: "https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_{}_{}.json.zip"
    # Source: https://www.geoboundaries.org/
    gbhumanitarian_url: "https://www.geoboundaries.org/api/current/gbHumanitarian/"
    # Source: https://www.geoboundaries.org/
    gbopen_url: "https://www.geoboundaries.org/api/current/gbOpen/"
    # https://hub.worldpop.org/geodata/listing?id=69
    worldpop_url: "https://data.worldpop.org/GIS/Population/Global_2000_2020/2020/{}/{}_ppp_2020_UNadj.tif"
    # Source: https://ucdp.uu.se/encyclopedia
    global_ucdp_url: "https://ucdp.uu.se/downloads/ged/ged251-csv.zip"
    # Source: https://datacatalog.worldbank.org/search/dataset/0037584
    global_landslide_url: "https://datacatalogfiles.worldbank.org/ddh-published/0037584/DR0045417/LS_TH_COG.tif"
    # Source: https://zenodo.org/records/8409647
    global_earthquake_url: "https://zenodo.org/records/8409647/files/GEM-GSHM_PGA-475y-rock_v2023.zip"
    # Source: https://data.humdata.org/dataset/cyclone-wind-100-years-return-period
    global_cyclone_url: "https://data.humdata.org/dataset/6366ac1f-6bed-42e9-b96e-22ef81008931/resource/202221dd-a79d-4ce5-93d7-f34f7514aeb2/download/viento-mundo-tr100-int1-g152.zip" 
    # Source: https://www.drought.gov/data-download
    global_drought_url: "https://storage.googleapis.com/noaa-nidis-drought-gov-data/current-conditions/tile/v1/ce-GLOBAL-ERA5_LAND_DAILY-speih-6mo/GLOBAL-ERA5_LAND_DAILY-speih-6mo.tif"
    # Source: https://zenodo.org/records/8310513
    global_heat_stress_url: "https://zenodo.org/records/8310513/files/GloUTCI-M_YEAR_2022_MONTH_10.zip"