osm_networks:
    roads:
        highway:
            - primary
            - secondary
            - tertiary
            - primary_link
            - secondary_link
            - tertiary_link
    waterways:
        waterway:
            - river
            - canal
            - fairway
    railways:
        - railway

osm_pois: 
    healthcare:
        - healthcare
        - amenity:
            - clinic
            - hospital
            - doctors
    airports:
        - aeroway:
            - terminal
            - gate
    markets:
        - shop:
            - supermarket
        - amenity:
            - marketplace
    public_service:
        - amenity:
            - townhall
            - police
            - fire_station
    financial_service:
        - amenity:
            - atm
            - payment_terminal
            - bank
            - bureau_de_change
            - money_transfer
            - payment_centre
        
    